### ISSUE TITLE
Couldn't Reproduce the Results

### ISSUE THREAD

**Issue by shambhavicodes** [gukyeongkwon/gradcon-anomaly#1]
I was trying to reproduce the results on CIFAR & MNIST Dataset following the shared instructions. However, the results were very different every time I ran the code and didn't match the ones shared in the paper.

Here's the result I got :
CIFAR - 10
0.7210 0.4727 0.6329 0.5940 0.7250 0.5682 0.6899 0.5220 0.7820 0.4518 0.6160
0.7595 0.5261 0.6065 0.5876 0.7026 0.5190 0.6954 0.5388 0.7505 0.5290 0.6215

MNIST 
0.9961 0.9991 0.9339 0.9540 0.5688 0.9554 0.4723 0.6632 0.9000 0.5773 0.8020
0.9964 0.9990 0.9241 0.9587 0.5663 0.9612 0.4717 0.6332 0.8967 0.5824 0.7990

**Comment by gukyeongkwon** [comment]
Hi, thanks for your interests in our paper. 

To obtain the same result for each run, you may want to define a random seed in the beginning of the code as follows. Also, the results may vary depending on the random seed.

```
parser.add_argument(
        "--seed", type=int, default=0, help="random seed for initialization"
    )

random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)
```
